import os
import json
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

DATASET_PATH = os.path.join(os.path.dirname(__file__), 'dataset.csv')
MOCK_JS_PATH = os.path.join(os.path.dirname(__file__), '..', 'frontend', 'src', 'mockData.js')

def main():
    if not os.path.exists(DATASET_PATH):
        print(f"Dataset not found at {DATASET_PATH}")
        return
    
    print("Reading dataset...")
    df = pd.read_csv(DATASET_PATH)
    
    # Original shape
    total_rows, total_cols = df.shape
    
    # Check nulls and duplicates
    null_counts = df.isnull().sum().to_dict()
    duplicate_count = int(df.duplicated().sum())
    
    # Clean df
    df_clean = df.drop_duplicates()
    
    # Stats for target order_value_eur
    target = 'order_value_eur'
    target_stats = {
        'mean': float(df_clean[target].mean()),
        'median': float(df_clean[target].median()),
        'max': float(df_clean[target].max()),
        'min': float(df_clean[target].min())
    }
    
    # Outliers count (IQR)
    q1 = df_clean[target].quantile(0.25)
    q3 = df_clean[target].quantile(0.75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    outliers_count = int(((df_clean[target] < lower_bound) | (df_clean[target] > upper_bound)).sum())
    
    # Descriptive stats
    features = ['quantity', 'discount_rate', 'avg_order_value_eur', 'previous_orders', 'customer_age_days', 'shipping_distance_km']
    key_cols = features + [target]
    desc_stats = {}
    stats_df = df_clean[key_cols].describe()
    for col in key_cols:
        desc_stats[col] = {
            'count': int(stats_df.loc['count', col]),
            'mean': float(stats_df.loc['mean', col]),
            'std': float(stats_df.loc['std', col]),
            'min': float(stats_df.loc['min', col]),
            'q1': float(stats_df.loc['25%', col]),
            'median': float(df_clean[col].median()),
            'q3': float(stats_df.loc['75%', col]),
            'max': float(stats_df.loc['max', col])
        }
        
    # Regression Model
    df_model = df_clean[key_cols].dropna()
    X = df_model[features]
    y = df_model[target]
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    model = LinearRegression()
    model.fit(X_train, y_train)
    
    y_pred = model.predict(X_test)
    mae = float(metrics.mean_absolute_error(y_test, y_pred))
    mse = float(metrics.mean_squared_error(y_test, y_pred))
    r2 = float(metrics.r2_score(y_test, y_pred))
    
    # Histogram
    counts, bins = np.histogram(df_clean[target], bins=20)
    histogram_data = {
        'counts': counts.tolist(),
        'bins': [round(float(b), 2) for b in bins]
    }
    
    # Real vs predicted sample
    test_results = pd.DataFrame({'Real': y_test, 'Pred': y_pred})
    sample_results = test_results.sample(min(150, len(test_results)), random_state=42)
    real_vs_pred = sample_results.to_dict(orient='records')
    
    # Correlation matrix
    corr_matrix = df_clean[key_cols].corr().round(3)
    correlation_data = {
        'columns': key_cols,
        'matrix': corr_matrix.values.tolist()
    }
    
    # Coefficients
    coef_dict = {feat: float(coef) for feat, coef in zip(features, model.coef_)}
    intercept = float(model.intercept_)
    
    # Sample records for preview table (first 250 records, clean and compact)
    df_sample = df.head(250).replace({np.nan: None})
    records_sample = df_sample.to_dict(orient='records')
    
    # Create JS file contents
    js_content = f"""// This file is auto-generated by generate_mock_js.py
// It provides fallback statistics, metadata, and regression weights for static deployments.

export const mockDatasetInfo = {{
  shape: [{total_rows}, {total_cols}],
  columns: {json.dumps(list(df.columns))},
  null_counts: {json.dumps(null_counts)},
  duplicate_count: {duplicate_count},
  target_stats: {json.dumps(target_stats)},
  outliers_count: {outliers_count},
  descriptive_stats: {json.dumps(desc_stats)}
}};

export const mockModelResults = {{
  metrics: {{
    mae: {mae:.4f},
    mse: {mse:.4f},
    r2: {r2:.4f}
  }},
  coefficients: {json.dumps(coef_dict)},
  intercept: {intercept:.4f},
  visualizations: {{
    histogram: {json.dumps(histogram_data)},
    real_vs_pred: {json.dumps(real_vs_pred)},
    correlation: {json.dumps(correlation_data)},
    importance: {json.dumps(coef_dict)}
  }}
}};

export const mockRecords = {json.dumps(records_sample, indent=2)};
"""
    
    # Ensure directory exists
    os.makedirs(os.path.dirname(MOCK_JS_PATH), exist_ok=True)
    with open(MOCK_JS_PATH, 'w', encoding='utf-8') as f:
        f.write(js_content)
        
    print(f"Mock JS file successfully written to {MOCK_JS_PATH}")

if __name__ == '__main__':
    main()
